apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
  labels:
    app: player-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: <your-registry>/player-service:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"